#!/usr/bin/env python

import sys

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print "I only accept a single argument."
        exit(0)

    with open("stl.txt", 'r') as f:
        lines = [line.strip() for line in f.readlines()]
        for line in lines:
            if sys.argv[1].lower() in line.lower():
                print line
